apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
spec:
  selector:
    matchLabels:
      app: postgres-deploy
  template:
    metadata:
      labels:
        app: postgres-deploy
    spec:
      containers:
      - name: postgres-deploy
        image: postgres
        ports:
        - containerPort: 5432
       # store all the values inside configmap 
        envFrom: 
          - configMapRef:
              name: postgres-demo-configmap
          - secretRef:
              name: postgres-demo-secret
