# Blue deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue-app
  labels: 
    app: demo-app
    replicas: blue 
spec:
  selector:
    matchLabels:
      app: demo-app
      replicas: blue 
  template:
    metadata:
      labels:
        app: demo-app
        replicas: blue 
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
