# this deployment only run and scale on node that has ssd 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-affinity-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: node-affinity-app
  template:
    metadata:
      labels:
        app: node-affinity-app
    # node1 , node5
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: disktype
                    operator: In 
                    values: 
                      - ssd 
      containers:
      - name: node-affinity-app
        image: nginx
        ports:
        - containerPort: 80
