# create the idempotent Ansible Playbook 
---
- name: Setup NFS Server 
  hosts: node1
  become: yes
  vars: 
    nfs_remote_dir: /srv/nfs_shared
    nfs_client_ips:
      - 192.168.56.11   
      - 192.168.56.12

  tasks: 
    - name: Update APT caches 
      apt: 
        update_cache: yes 
    - name: Install NFS Kernel Server 
      apt: 
        name: nfs-kernel-server
        state: present 
    - name: Create Directory to used 
      file: 
        path: "{{ nfs_remote_dir }}"
        state: directory
        owner: nobody
        group: nogroup
        mode: "0777"
    # configuration inside /etc/exports ( tell which clients can use  it)
    - name: Configure the NFS Server exports 
      blockinfile: 
        path: /etc/exports
        block: |
          {{ nfs_remote_dir }} {{ export_entries }}
        create: yes 
        state: present 
      vars: 
        export_entries: >-
          {{ nfs_client_ips | map('regex_replace', '^(.*)$', '\g<1>(rw,sync,no_subtree_check,no_root_squash)') | join(' ') }}
    - name: Apply Configuration 
      command: exportfs -ra 
    - name: Restart NFS Kernel Service 
      systemd: 
        name: nfs-kernel-server
        enabled: true 
        state: restarted 

# ansible-playbook -i inventory.ini playbooks/nfs_server.yaml