apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nignx-replicaset
  labels: 
    app: nginx-replicas-app
spec:
  replicas: 3 # define the numbers of pod you want to keep
  selector:
    matchLabels:
      app: nginx-replicas-app
  template:
    metadata:
      labels:
        app: nginx-replicas-app
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports: 
            - containerPort: 80
# kubectl apply -f nginx-replica.yaml 