# spring deployment that uses nfs 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      # affinity:
      #   nodeAffinity:
      #       requiredDuringSchedulingIgnoredDuringExecution:
      #         nodeSelectorTerms:
      #         - matchExpressions:
      #           - key: kubernetes.io/hostname
      #             operator: NotIn
      #             values:
      #             - node1 # master1
      containers:
      - name: spring-app-cont
        #image: 69966/springgradleimg:1.1.1
        image: 69966/springgradleimg:1.1.1
        volumeMounts: 
          - name: my-image-vol
            mountPath: /app/src/main/resources/images
        ports:
        - containerPort: 8080
      volumes: 
        - name: my-image-vol
          nfs:
            # change to your actual server ip  
            server: 10.148.0.2
            path: /srv/nfs_shared/my_spring_storage