apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      # nodeSelector: 
      #   kubernetes.io/hostname: node1
      containers:
      - name: spring-app
        image: 69966/springgradleimg:1.1.1 
        ports:
        - containerPort: 8080
        volumeMounts: 
          - name: my-vol 
            # path inside the container 
            mountPath: app/src/main/resources/images
      volumes: 
        - name: my-vol
          hostPath: 
            path: /var/spring_images

