#!/bin/bash

render-prod: 
    helm template custom-chart \
        --values custom-chart/prod-values.yaml 

render-stag: 
    helm template custom-chart \
        --values custom-chart/stagging-values.yaml 

install-stag: 
    helm upgrade custom-release custom-chart \
        --values custom-chart/stagging-values.yaml --install

install-prod: 
    helm upgrade custom-release custom-chart \
        --values custom-chart/prod-values.yaml --install
