#!/bin/bash

render-prod: 
    helm template custom-chart \
        --values custom-chart/prod-values.yaml 

render-stag: 
    helm template custom-chart \
        --values custom-chart/stagging-values.yaml 
        